name: 2) QA
on:
  workflow_dispatch:
    
env:
  SCRIPTS_HOME: /apps/scripts
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_URL: ${{ github.event.repository.html_url }}
  PUSHER: ${{ github.actor }}
  DEPLOY_ENV: QA
jobs:
  deploy-qa:
    runs-on:
      - ipaas-applications
    environment: QA
    steps:
      -
        name: Echo Deploy Script
        run: echo python3 $SCRIPTS_HOME/deployAppV3.py deploy $REPO_NAME $DEPLOY_ENV $GITHUB_WORKSPACE
      -
        name: Call Deploy Script
        run: python3 $SCRIPTS_HOME/deployAppV3.py deploy $REPO_NAME $DEPLOY_ENV $GITHUB_WORKSPACE
  squawk-qa:
    runs-on:
      - ipaas-applications
    environment: QA
    needs: deploy-qa
    steps:
      -
        name: Squawk
        run: $SCRIPTS_HOME/SquawkV2.sh $REPO_NAME 12258 $REPO_URL $PUSHER $GITHUB_SHA $DEPLOY_ENV
  test-qa:
    runs-on:
      - ipaas-applications
    environment: QA
    needs: squawk-qa
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Echo Postman Test
        run: |
         echo /apps/scripts/newman_tests.sh -l$GITHUB_WORKSPACE -a$REPO_NAME -e$DEPLOY_ENV

      -
        name: Postman Test
        run: |
         echo /apps/scripts/newman_tests.sh -l$GITHUB_WORKSPACE -a$REPO_NAME -e$DEPLOY_ENV
